"""Deterministic RG-PCNet training defaults."""

SEED = 42
INPUT_DIM = 112
HIDDEN_DIM = 128
DROPOUT = 0.20
BATCH_SIZE = 8
EPOCHS = 40
PATIENCE = 6
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-4
GRAD_CLIP_NORM = 1.0
NUM_WORKERS = 0
CORRUPTION_PROBABILITY = 0.50
