import base64
import copy
import json
import math
import pickle
from dataclasses import asdict, fields
from decimal import Decimal

import numpy as np
import pytest

import risk.phase_model.rg_calibration as rg_calibration
from risk.phase_model.rg_calibration import (
    CalibrationArtifact,
    _temperature_candidates,
    fit_bounded_temperature,
)


# Protocol-5 fixtures generated by executing the exact rg_calibration.py source
# at 9d3ca7c5d90b9f28b6e00232a508769cb1270170. The second and third fixtures
# were then corrupted through that version's live class_counts/__dict__ state.
_LEGACY_VALID_PICKLE = base64.b64decode(
    "gAWVTwEAAAAAAACMH3Jpc2sucGhhc2VfbW9kZWwucmdfY2FsaWJyYXRpb26UjBND"
    "YWxpYnJhdGlvbkFydGlmYWN0lJOUKYGUfZQojAt0ZW1wZXJhdHVyZZRHP+AAAAAA"
    "AACMB2VuYWJsZWSUiIwGcmVhc29ulIwhY2FsaWJyYXRpb24gaW1wcm92ZWQgbmxs"
    "IG9yIGJyaWVylIwMc2FtcGxlX2NvdW50lEsCjAxjbGFzc19jb3VudHOUaACMFV9J"
    "bW11dGFibGVDbGFzc0NvdW50c5STlH2UKIwBMJRLAYwBMZRLAXWFlFKUjApubGxf"
    "YmVmb3JllEc/1Ax6v77BJYwJbmxsX2FmdGVylEc/wD8tVDAdSYwMYnJpZXJfYmVm"
    "b3JllEc/soQvcgxi8IwLYnJpZXJfYWZ0ZXKURz+NGcjgmStYjApzcGxpdF9oYXNo"
    "lIwDYWJjlHViLg=="
)
_LEGACY_MALFORMED_COUNTS_PICKLE = base64.b64decode(
    "gAWVTwEAAAAAAACMH3Jpc2sucGhhc2VfbW9kZWwucmdfY2FsaWJyYXRpb26UjBND"
    "YWxpYnJhdGlvbkFydGlmYWN0lJOUKYGUfZQojAt0ZW1wZXJhdHVyZZRHP+AAAAAA"
    "AACMB2VuYWJsZWSUiIwGcmVhc29ulIwhY2FsaWJyYXRpb24gaW1wcm92ZWQgbmxs"
    "IG9yIGJyaWVylIwMc2FtcGxlX2NvdW50lEsCjAxjbGFzc19jb3VudHOUaACMFV9J"
    "bW11dGFibGVDbGFzc0NvdW50c5STlH2UKIwBMJRLAowBMZRLAnWFlFKUjApubGxf"
    "YmVmb3JllEc/1Ax6v77BJYwJbmxsX2FmdGVylEc/wD8tVDAdSYwMYnJpZXJfYmVm"
    "b3JllEc/soQvcgxi8IwLYnJpZXJfYWZ0ZXKURz+NGcjgmStYjApzcGxpdF9oYXNo"
    "lIwDYWJjlHViLg=="
)
_LEGACY_UNKNOWN_KEY_PICKLE = base64.b64decode(
    "gAWVawEAAAAAAACMH3Jpc2sucGhhc2VfbW9kZWwucmdfY2FsaWJyYXRpb26UjBND"
    "YWxpYnJhdGlvbkFydGlmYWN0lJOUKYGUfZQojAt0ZW1wZXJhdHVyZZRHP+AAAAAA"
    "AACMB2VuYWJsZWSUiIwGcmVhc29ulIwhY2FsaWJyYXRpb24gaW1wcm92ZWQgbmxs"
    "IG9yIGJyaWVylIwMc2FtcGxlX2NvdW50lEsCjAxjbGFzc19jb3VudHOUaACMFV9J"
    "bW11dGFibGVDbGFzc0NvdW50c5STlH2UKIwBMJRLAYwBMZRLAXWFlFKUjApubGxf"
    "YmVmb3JllEc/1Ax6v77BJYwJbmxsX2FmdGVylEc/wD8tVDAdSYwMYnJpZXJfYmVm"
    "b3JllEc/soQvcgxi8IwLYnJpZXJfYWZ0ZXKURz+NGcjgmStYjApzcGxpdF9oYXNo"
    "lIwDYWJjlIwKdW5leHBlY3RlZJSMDGxlZ2FjeS1leHRyYZR1Yi4="
)


def test_single_class_calibration_falls_back_to_identity():
    result = fit_bounded_temperature([2.0, 3.0], [1, 1], split_hash="abc")
    assert result.temperature == 1.0
    assert result.enabled is False
    assert result.reason == "calibration requires both classes"
    assert result.class_counts == {"0": 0, "1": 2}


def test_temperature_is_bounded_and_only_enabled_when_nll_improves():
    result = fit_bounded_temperature([4.0, -4.0, -2.0, 2.0], [1, 0, 1, 0], split_hash="abc")
    assert 0.5 <= result.temperature <= 5.0
    if result.enabled:
        assert result.nll_after < result.nll_before
    else:
        assert result.temperature == 1.0


def test_temperature_grid_has_exact_count_and_endpoints():
    candidates = _temperature_candidates()
    log_steps = [math.log(right / left) for left, right in zip(candidates, candidates[1:])]

    assert len(candidates) == 181
    assert candidates[0] == pytest.approx(0.5)
    assert candidates[-1] == pytest.approx(5.0)
    assert candidates[45] == pytest.approx(0.5 * 10 ** 0.25)
    assert candidates[90] == pytest.approx(0.5 * math.sqrt(10.0))
    assert max(log_steps) - min(log_steps) < 1e-15
    assert all(0.5 <= value <= 5.0 for value in candidates)
    assert all(left < right for left, right in zip(candidates, candidates[1:]))


@pytest.mark.parametrize(
    ("logits", "labels"),
    [([], []), ([1.0], []), ([1.0], [0, 1])],
)
def test_fit_rejects_empty_or_mismatched_inputs(logits, labels):
    with pytest.raises(ValueError, match="non-empty and have the same length"):
        fit_bounded_temperature(logits, labels, split_hash="abc")


@pytest.mark.parametrize("labels", [[0, 2], [-1, 1], [0.5, 1], ["0", 1], [math.nan, 1]])
def test_fit_rejects_non_binary_labels(labels):
    with pytest.raises(ValueError, match="binary"):
        fit_bounded_temperature([1.0, -1.0], labels, split_hash="abc")


@pytest.mark.parametrize("split_hash", [None, "", "   ", 123])
def test_fit_rejects_missing_split_hash(split_hash):
    with pytest.raises(ValueError, match="split_hash must be a non-empty string"):
        fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash=split_hash)


def test_nonfinite_fit_data_returns_finite_identity_fallback():
    result = fit_bounded_temperature(
        [math.nan, math.inf, -math.inf, 0.0],
        [1, 0, 1, 0],
        split_hash="abc",
    )

    assert result.temperature == 1.0
    assert result.enabled is False
    assert result.reason == "calibration data contains non-finite logits"
    assert result.nll_after == result.nll_before
    assert result.brier_after == result.brier_before
    assert all(
        math.isfinite(value)
        for value in (
            result.nll_before,
            result.nll_after,
            result.brier_before,
            result.brier_after,
        )
    )


def test_nonfinite_audit_metrics_preserve_infinity_sign():
    aligned = fit_bounded_temperature(
        [math.inf, -math.inf], [1, 0], split_hash="abc"
    )
    opposite = fit_bounded_temperature(
        [-math.inf, math.inf], [1, 0], split_hash="abc"
    )

    assert aligned.nll_before < opposite.nll_before
    assert aligned.brier_before < opposite.brier_before
    assert aligned.nll_after == aligned.nll_before
    assert opposite.nll_after == opposite.nll_before
    assert all(
        math.isfinite(value)
        for result in (aligned, opposite)
        for value in (
            result.nll_before,
            result.nll_after,
            result.brier_before,
            result.brier_after,
        )
    )


def test_nan_audit_metrics_are_conservative_against_each_label():
    aligned_infinities = fit_bounded_temperature(
        [math.inf, -math.inf], [1, 0], split_hash="abc"
    )
    unknown_logits = fit_bounded_temperature(
        [math.nan, math.nan], [1, 0], split_hash="abc"
    )

    assert unknown_logits.nll_before > aligned_infinities.nll_before
    assert unknown_logits.brier_before > aligned_infinities.brier_before
    assert unknown_logits.nll_after == unknown_logits.nll_before
    assert unknown_logits.brier_after == unknown_logits.brier_before


def test_no_improvement_returns_identity_metrics():
    result = fit_bounded_temperature([0.0, 0.0], [0, 1], split_hash="abc")

    assert result.enabled is False
    assert result.temperature == 1.0
    assert result.reason == "calibration did not improve nll or brier"
    assert result.nll_after == result.nll_before
    assert result.brier_after == result.brier_before


def test_artifact_snapshots_and_freezes_caller_owned_class_counts():
    class_counts = {"0": 1, "1": 1}
    artifact = CalibrationArtifact(
        temperature=1.0,
        enabled=False,
        reason="identity",
        sample_count=2,
        class_counts=class_counts,
        nll_before=0.5,
        nll_after=0.5,
        brier_before=0.25,
        brier_after=0.25,
        split_hash="abc",
    )

    class_counts["0"] = 99
    assert artifact.class_counts == {"0": 1, "1": 1}
    with pytest.raises(TypeError):
        artifact.class_counts["0"] = 99
    with pytest.raises(TypeError):
        artifact.class_counts.update({"0": 99})


def _mutate_with_ior(class_counts):
    class_counts |= {"0": 99}


def test_class_counts_block_reinitialization_and_public_mutators():
    artifact = fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash="abc")
    class_counts = artifact.class_counts

    mutations = (
        lambda: class_counts.__init__({"0": 9, "1": 9}),
        lambda: class_counts.__setitem__("0", 9),
        lambda: class_counts.update({"0": 9}),
        lambda: class_counts.pop("0"),
        lambda: _mutate_with_ior(class_counts),
    )
    for mutate in mutations:
        with pytest.raises(TypeError, match="immutable"):
            mutate()
        assert class_counts == {"0": 1, "1": 1}


def test_class_counts_support_copy_asdict_json_and_pickle_round_trips():
    artifact = fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash="abc")
    class_counts = artifact.class_counts

    assert copy.copy(class_counts) is class_counts
    assert copy.deepcopy(class_counts) is class_counts
    assert copy.copy(artifact) == artifact
    assert copy.deepcopy(artifact) == artifact

    payload = asdict(artifact)
    assert payload["class_counts"] == {"0": 1, "1": 1}
    assert json.loads(json.dumps(payload)) == payload

    restored = pickle.loads(pickle.dumps(artifact))
    assert restored == artifact
    with pytest.raises(TypeError, match="immutable"):
        restored.class_counts["0"] = 9


def test_base_dict_bypasses_only_mutate_a_detached_class_counts_snapshot():
    artifact = fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash="abc")
    snapshot = artifact.class_counts

    dict.__setitem__(snapshot, "0", 9)
    assert snapshot == {"0": 9, "1": 1}
    assert artifact.class_counts == {"0": 1, "1": 1}

    dict.__init__(snapshot, {"0": 0, "1": 2})
    assert snapshot == {"0": 0, "1": 2}
    assert artifact.class_counts == {"0": 1, "1": 1}
    assert artifact.class_counts is not artifact.class_counts
    assert artifact.sample_count == sum(artifact.class_counts.values()) == 2

    payload = asdict(artifact)
    assert payload["class_counts"] == {"0": 1, "1": 1}
    assert json.loads(json.dumps(payload))["class_counts"] == {"0": 1, "1": 1}
    assert "class_counts={'0': 1, '1': 1}" in repr(artifact)
    assert dict(artifact.class_counts) == {"0": 1, "1": 1}


def test_detached_counts_survive_artifact_copy_and_pickle_round_trips():
    artifact = fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash="abc")
    copies = (
        copy.copy(artifact),
        copy.deepcopy(artifact),
        pickle.loads(pickle.dumps(artifact)),
    )

    for copied in copies:
        exposed = copied.class_counts
        dict.__init__(exposed, {"0": 2, "1": 0})
        assert copied.class_counts == {"0": 1, "1": 1}
        assert copied == artifact
        with pytest.raises(TypeError, match="immutable"):
            copied.class_counts.update({"0": 2})


def test_genuine_legacy_pickle_migrates_to_detached_canonical_counts():
    artifact = pickle.loads(_LEGACY_VALID_PICKLE)
    snapshot = artifact.class_counts

    dict.__setitem__(snapshot, "0", 9)
    dict.__init__(snapshot, {"0": 0, "1": 2})

    assert artifact.class_counts == {"0": 1, "1": 1}
    assert artifact.sample_count == sum(artifact.class_counts.values()) == 2
    payload = asdict(artifact)
    assert payload["class_counts"] == {"0": 1, "1": 1}
    assert json.loads(json.dumps(payload))["class_counts"] == {"0": 1, "1": 1}
    assert "class_counts" not in vars(artifact)
    assert vars(artifact)["_class_counts_values"] == (1, 1)


@pytest.mark.parametrize(
    "legacy_pickle",
    [_LEGACY_MALFORMED_COUNTS_PICKLE, _LEGACY_UNKNOWN_KEY_PICKLE],
)
def test_malformed_genuine_legacy_pickle_fails_deterministically(legacy_pickle):
    with pytest.raises(ValueError, match="invalid calibration artifact pickle state"):
        pickle.loads(legacy_pickle)


@pytest.mark.parametrize("protocol", range(6))
def test_current_pickle_protocols_preserve_detached_counts(protocol):
    artifact = fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash="abc")

    restored = pickle.loads(pickle.dumps(artifact, protocol=protocol))
    snapshot = restored.class_counts
    dict.__init__(snapshot, {"0": 2, "1": 0})

    assert restored == artifact
    assert restored.class_counts == {"0": 1, "1": 1}
    assert "class_counts" not in vars(restored)
    assert vars(restored)["_class_counts_values"] == (1, 1)


def test_class_counts_remains_an_exact_named_dataclass_field():
    assert [field.name for field in fields(CalibrationArtifact)] == [
        "temperature",
        "enabled",
        "reason",
        "sample_count",
        "class_counts",
        "nll_before",
        "nll_after",
        "brier_before",
        "brier_after",
        "split_hash",
    ]


def test_artifact_normalizes_decimal_and_numpy_metrics_for_json():
    artifact = CalibrationArtifact(
        temperature=1.0,
        enabled=False,
        reason="identity",
        sample_count=2,
        class_counts={"0": 1, "1": 1},
        nll_before=Decimal("0.5"),
        nll_after=np.float32(0.5),
        brier_before=Decimal("0.25"),
        brier_after=np.float32(0.25),
        split_hash="abc",
    )

    assert all(
        type(getattr(artifact, name)) is float
        for name in ("nll_before", "nll_after", "brier_before", "brier_after")
    )
    payload = asdict(artifact)
    assert json.loads(json.dumps(payload)) == payload


@pytest.mark.parametrize("metric", [object(), Decimal("NaN")])
def test_artifact_rejects_invalid_metrics_with_stable_value_error(metric):
    with pytest.raises(ValueError, match="calibration metrics must be finite numbers"):
        CalibrationArtifact(
            temperature=1.0,
            enabled=False,
            reason="identity",
            sample_count=2,
            class_counts={"0": 1, "1": 1},
            nll_before=metric,
            nll_after=0.5,
            brier_before=0.25,
            brier_after=0.25,
            split_hash="abc",
        )


def test_calibrate_returns_independent_output_and_rejects_nonfinite_logits():
    artifact = fit_bounded_temperature([0.0, 0.0], [0, 1], split_hash="abc")
    logits = [0.0]

    probabilities = artifact.calibrate(logits)
    logits[0] = 10.0

    assert probabilities == [0.5]
    with pytest.raises(ValueError, match="finite"):
        artifact.calibrate([math.nan])
    with pytest.raises(ValueError, match="finite"):
        artifact.calibrate([math.inf])


def test_large_logits_produce_stable_probabilities_and_finite_metrics():
    result = fit_bounded_temperature(
        [1e300, -1e300, 1e300, -1e300],
        [1, 0, 0, 1],
        split_hash="abc",
    )

    assert result.calibrate([1e300, -1e300, 0.0]) == [1.0, 0.0, 0.5]
    assert all(
        math.isfinite(value)
        for value in (
            result.nll_before,
            result.nll_after,
            result.brier_before,
            result.brier_after,
        )
    )


def test_fit_is_deterministic_for_repeated_inputs():
    logits = [4.0, -4.0, -2.0, 2.0]
    labels = [1, 0, 1, 0]

    first = fit_bounded_temperature(logits, labels, split_hash="abc")
    second = fit_bounded_temperature(tuple(logits), tuple(labels), split_hash="abc")

    assert first == second


def test_enabled_artifact_has_real_metric_improvement():
    result = fit_bounded_temperature([4.0, -4.0, -2.0, 2.0], [1, 0, 1, 0], split_hash="abc")

    assert result.enabled is True
    assert 0.5 <= result.temperature <= 5.0
    assert (
        result.nll_after < result.nll_before - 1e-6
        or result.brier_after < result.brier_before - 1e-6
    )


def test_brier_only_improvement_enables_calibration(monkeypatch):
    monkeypatch.setattr(rg_calibration, "_temperature_candidates", lambda: (2.0,))
    monkeypatch.setattr(
        rg_calibration,
        "_metrics",
        lambda _logits, _labels, temperature: (
            (0.5, 0.25) if temperature == 1.0 else (0.5, 0.20)
        ),
    )

    result = fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash="abc")

    assert result.enabled is True
    assert result.temperature == 2.0
    assert result.nll_after == result.nll_before
    assert result.brier_after < result.brier_before - 1e-6


def test_improvement_equal_to_epsilon_does_not_enable(monkeypatch):
    monkeypatch.setattr(rg_calibration, "_temperature_candidates", lambda: (2.0,))
    monkeypatch.setattr(
        rg_calibration,
        "_metrics",
        lambda _logits, _labels, temperature: (
            (1.0, 0.25) if temperature == 1.0 else (1.0 - 1e-6, 0.25)
        ),
    )

    result = fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash="abc")

    assert result.enabled is False
    assert result.temperature == 1.0
    assert result.nll_after == result.nll_before


@pytest.mark.parametrize("candidate_order", [(2.0, 0.5), (0.5, 2.0)])
def test_metric_ties_choose_lower_equidistant_temperature_deterministically(
    monkeypatch, candidate_order
):
    monkeypatch.setattr(
        rg_calibration, "_temperature_candidates", lambda: candidate_order
    )
    monkeypatch.setattr(
        rg_calibration,
        "_metrics",
        lambda _logits, _labels, temperature: (
            (1.0, 0.5) if temperature == 1.0 else (0.9, 0.4)
        ),
    )

    result = fit_bounded_temperature([1.0, -1.0], [1, 0], split_hash="abc")

    assert result.enabled is True
    assert result.temperature == 0.5
